apiVersion: v1
kind: Secret
metadata:
  name: fleet-status-backend-secret
  namespace: fleet-status
type: Opaque
stringData:
  THANOS_URL: "https://rbac-query-proxy.open-cluster-management-observability.svc.cluster.local"
  THANOS_TOKEN: ""
  THANOS_CA_FILE: "/etc/thanos-ca/ca.crt"
